# AND-GATE using-PERCEPTRON

# What is a Perceptron ?
A Perceptron is an algorithm used for supervised learning of binary classifiers. 
Binary classifiers decide whether an input, usually represented by a series of vectors, belongs to a specific class.

In short, a perceptron is a single-layer neural network. 
They consist of four main parts including input values, weights and bias, net sum, and an activation function.

<img src="Single-Perceptron.png"/>

# AND GATE

The output will be high only if both the inputs are high
<img src="AND-GATE.jpg">

In [114]:
import numpy as np

In [115]:
input=np.array([[1,1,1],[1,0,1],[0,1,1],[0,0,1]]) # size 4,3
output=np.array([[1],[-1],[-1],[-1]])

In [116]:
w1=np.array(np.random.random((3,1)))

In [117]:
w1

array([[0.57020818],
       [0.33611948],
       [0.65536547]])

In [118]:
epochs=0
max_epochs=10

In [119]:
#Activation functions or step functions are decision making units of neural networks
def step(x):
    is_greator=np.float(np.greater(x,0))
    doubled=np.multiply(is_greator,2)
    return np.subtract(doubled,1)    

In [120]:
while epochs < max_epochs:
    epochs+=1
    o1=np.matmul(input,w1) #output o1 is matrix multiplication of input with weights
    func=np.vectorize(step)
    t1=func(o1) # t1 is thresholded output using step function
    error=np.subtract(output,t1)
    print(t1)
    mse=np.mean(np.square(error))
    print(mse)
    if mse==0:
        break
    #delta calculation
    delta=np.matmul(input.transpose(),error) #size 3,1
    w1=np.add(w1, delta)

[[1.]
 [1.]
 [1.]
 [1.]]
3.0
[[-1.]
 [-1.]
 [-1.]
 [-1.]]
1.0
[[-1.]
 [-1.]
 [-1.]
 [-1.]]
1.0
[[ 1.]
 [ 1.]
 [ 1.]
 [-1.]]
2.0
[[-1.]
 [-1.]
 [-1.]
 [-1.]]
1.0
[[ 1.]
 [-1.]
 [-1.]
 [-1.]]
0.0
