# OR-GATE Using-Perceptron
output will be high if any of the input is high

<img src="OR-gate.png">

In [7]:
import numpy as np

input=np.array([[1,1,1],[1,0,1],[0,1,1],[0,0,1]])
output=np.array([[1],[1],[1],[-1]])
w1=np.array(np.random.random((3,1)))
epochs=0
max_epochs=10


In [8]:

def step(x):
    is_greator=np.float(np.greater(x,0))
    doubled=np.multiply(is_greator,2)
    return np.subtract(doubled,1)


In [9]:

while epochs<max_epochs:
    epochs+=1

    z1=np.matmul(input,w1)
    func=np.vectorize(step)
    t1=func(z1)
    error=np.subtract(output,t1)
    print(t1)
    mse=np.mean(np.square(error))
    print(mse)
    if mse==0:
        break
    #delta calculation
    delta=np.matmul(input.transpose(),error)
    w1=np.add(w1,delta)

[[1.]
 [1.]
 [1.]
 [1.]]
1.0
[[-1.]
 [-1.]
 [-1.]
 [-1.]]
3.0
[[1.]
 [1.]
 [1.]
 [1.]]
1.0
[[1.]
 [1.]
 [1.]
 [1.]]
1.0
[[1.]
 [1.]
 [1.]
 [1.]]
1.0
[[ 1.]
 [ 1.]
 [ 1.]
 [-1.]]
0.0
